name: 'create-unitypackage'
description: 'This action sets up an Unity Editor for use in actions'
author: 'pCYSl5EDgo'
inputs:
  package-path:
    description: 'Output unitypackage file path'
    required: true
  include-files:
    description: 'Relative file paths from project-folder. Multi-line string value. Each line should ends with .meta.'
    required: true
  project-folder:
    description: 'Unity project folder. Default => ./'
    required: false
  working-folder:
    description: 'The working folder where this Node.js script runs. Please keep in mind that this script changes directory at first.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
